#撤离计划外部环境

#撤离模拟开始现实时间
real_time: '8:00'

#台风等级
typhoon_level: 1

#台风中心位置
typhoon_center: [117.5, 26.5]

#台风移动速度
typhoon_speed: 10

#台风移动方向
typhoon_direction: 90

#台风半径
typhoon_radius: 100

#特殊时间段
special_time: '12:00'
